theme: jekyll-theme-minimal
title: Rohit's Blog
description: selected open source projects 
logo: http://github.com/srohit0.png
google_analytics: UA-143240948-1 

# theme: jekyll-theme-time-machine
# title: Rohit's Blog
# description: selected open source projects 
# google_analytics: UA-143240948-1
